name: backupz
base: core18
version: '0.0.1'
summary: Backupz create zip archive with backup
description: |
  * Select dirs
  * Select files
  * Exclude by regex (zip -x)
  * Save backup to dir
  * Save backup to ftp

grade: stable
confinement: strict

parts:
  backupz:
    plugin: dump
    source: scripts
    organize:
      run.sh: bin/
      functions.sh: bin/
      config.json: bin/

    stage-packages:
      - jq
      - zip
      - ncftp

apps:
  backupz:
    command: bin/run.sh
    plugs:
      - home
      - network
