name: backupz
base: core18
version: '0.0.3'
summary: Backupz create backup tar.gz archive
description: |
  * Select dirs
  * Select files
  * Exclude by regex (tar --exclude)
  * Save backup to dir
  * Save backup to ftp
  * Multiple processes

grade: stable
confinement: strict

parts:
  backupz:
    plugin: dump
    source: scripts
    organize:
      run.sh: bin/
      functions.sh: bin/
      config.json: bin/

    stage-packages:
      - jq
      - ncftp
      - pigz
      - tar

apps:
  backupz:
    command: bin/run.sh
    plugs:
      - home
      - network
